// settings.gradle
pluginManagement {
    repositories {
        maven {
            name = 'Modrinth'
            url = 'https://maven.modrinth.com'
        }
        maven { 
            name = 'Fabric Gitee Mirror'
            url = 'https://gitee.com/mirrors_fabric/maven/raw/master/' 
        }
        gradlePluginPortal()
    }
}
